### ISSUE TITLE
Could not init X display

### ISSUE THREAD

**Issue by Qwertylex** [geofft/linmodem#1]
>./lm -sv
>A 16 bit visual is need by this program
>Could not init X display

OS: Arch Linux 
Kernel: x86_64 Linux 4.8.13-1-ARCH
Shell: bash 4.4.5
Resolution: 1920x1080
WM: GNOME Shell
WM Theme: Adwaita
CPU: Intel Core i7 CPU Q 740 @ 1.734GHz
GPU: Quadro FX 1800M
RAM: 10790MiB / 15986MiB

**Comment by davisRoman** [comment]
Comment out 'USE_X11=y' in Makefile to disable X11 debug interface

**Comment by geofft** [comment]
I'm not the linmodem maintainer and this isn't the official Linmodem repository (it's a copy I made for some personal experiments), see if there's a place to report this at http://www.linmodems.org or https://bellard.org/linmodem/ ?
